### ISSUE TITLE
Remapify vs paths

### ISSUE THREAD

**Issue by ganchenkor** [thejameskyle/marionette-wires#17]
I saw you are doing remapify plugin for avoiding `require('../'../')`, another way would be
https://github.com/thejameskyle/marionette-wires/blob/master/gulpfile.js#L42

<pre>
path = require('path') //By default in node.js
bundler = watchify(browserify('./src/main.js', _.extend({
debug: true,
<b>paths: [path.resolve('./src')]</b>
 }, watchify.args)));
</pre>

**Comment by thejameskyle** [comment]
I believe `paths` is no longer recommended. I'll eventually be removing remapify as well.

**Comment by joshbedo** [comment]
there is still a reference to `remapify` inside the gulpfile.js

**Comment by thejameskyle** [comment]
Whoops, fixed.
