### ISSUE TITLE
NPM Install: Browserify peerDependencies requirements.

### ISSUE THREAD

**Issue by calmdev** [thejameskyle/marionette-wires#24]
Hey guys,

Trying to learn with `marionette-wires`. I'm running into an issue with NPM install:

![screen shot 2015-01-09 at 10 33 29 am](https://cloud.githubusercontent.com/assets/461249/5682002/01360e9c-97eb-11e4-85dc-34768c1cb076.png)

I've tried changing the browserify version, but when I do so, there is no `bundle.js` after running `gulp` and nothing is bound to port 9000 either. So far I've been having a hard-time just trying to get the project loaded in the browser.

Any help I can get to get this running would be appreciated!

**Comment by samccone** [comment]
yeah fairly sure this is due to npm 2.x release changing how peer-deps work, we prob just need to update the versions to make it all work again

**Comment by calmdev** [comment]
If I bump browserify to 7.0.0, NPM install works fine, but it's not clear to me if gulp is working properly. I don't see a `bundle.js` in dist and still no application bound to port 9000. If I can get it working I'd love to commit the changes back to the project.

![screen shot 2015-01-09 at 10 49 53 am](https://cloud.githubusercontent.com/assets/461249/5682345/47d61a98-97ed-11e4-9ea5-5de9684d172c.png)

**Comment by calmdev** [comment]
If try what's suggested in #17 I no longer get the `write after end error`, but still the application doesn't run. Where does it actually bind to port 9000?

**Comment by joshbedo** [comment]
@calmdev it looks like you're still getting an error on `layout-template.hbs` which is causing the `dist/bundle.js` not to be created. I upgraded browserify to 7.0.0 and also replaced remapify with [#17](https://github.com/thejameskyle/marionette-wires/issues/17) and see the same error. It looks like it's confused on how to parse the hbs templates with browserify.

**Comment by calmdev** [comment]
@joshbedo I ended up using the application's structure, but around my own tooling - grunt instead of gulp, webpack instead of browserify and linkedin's fork of dustjs instead of handlebars.

**Comment by thejameskyle** [comment]
Fixed.

**Comment by calmdev** [comment]
It builds now, thanks!
