### ISSUE TITLE
New structure?

### ISSUE THREAD

**Issue by thejameskyle** [thejameskyle/marionette-wires#26]
We've been switching to a new structure at CloudFlare which I really like. Here's what it would be when applied to the wires repo.

Top level: `index.js` is the entry file, `plugins.js` is the setup for all plugins.
```
/src/
  index.js
  plugins.js
  /common/
  /components/
  /modules/
```

Common: A bit open ended, but more restrictions should be added on what is allowed to be here.
```
/common/
  /lib/
    foo.js
  /test/
    foo.js
```

Components and Modules: `components/` is for pieces of the application that are common across `modules/` which are distinct sections of the application which have routes tied to them.
```
/components/
  /flashes/
  /header/
  /modal/
/modules/
  /books/
  /colors/
  /index/
```
Each of these subdirectories are broken up as the following. An `index.js` entry file for the contents of `lib/` which make up all of the assets needed for that module, which are then tested in `test/`.

```js
/books/
  index.js
  /lib/
  /test/
```

Then `lib/` is broken down like this:

```
/lib/
  module.js
  router.js
  /collections/
  /models/
  /routes/
  /templates/  
  /views/
```

Which you would then match in `test/`

```
/test/
  module.js
  router.js
  /collections/
  /models/
  /routes/
  /templates/  
  /views/
```

**Comment by joshbedo** [comment]
Little unclear on the `common` directory, is that still going to contain wrappers for Marionette classes? Wondering what you would need tests for if the common files simply do something like
```
var Marionette = require('backbone.marionette')
module.exports = Marionette.CollectionView;
```

Curious about what would be inside of the index.js entry point for each component/module? I like the structure overall :+1:

**Comment by thejameskyle** [comment]
> is that still going to contain wrappers for Marionette classes? 

Yes

> Wondering what you would need tests for if the common files simply do something like [...]

Most apps will have more on this end. That folder should probably be broken down into `lib` and `test` as well.

**Comment by megawac** [comment]
I'm not a big fan of this, I prefer the current structure as I feel it scales better for large applications (I built a large app with the structure your proposing [but sans Mn] and one similar to the current structure).

For instance, the current structure makes defining subviews and subapplications quite logical

I'll elaborate when I woke up (on the 11th straight hour of a report at the moment :z)

**Comment by dnewkerk** [comment]
I really like the new proposed structure. I'm just getting started with marionette-wires and was having a bit of difficulty following the current structure. As soon as I viewed your proposed structure, various puzzle pieces snapped into place for me. For me the most helpful aspect is easily identifying what things are reusable components, what are higher level modules, etc.

Looking forward to it (or whatever similar changes may be in store). In any case I think I will adjust my own app to something along these lines. Thanks for all your great work :)

**Comment by thejameskyle** [comment]
Closing this as part of cleaning out old issues. Feel free to continue to comment.

**Comment by VladimirPal** [comment]
@thejameskyle When we can see this structure?
