### ISSUE TITLE
onDomRefresh and onAttach not fired in modal views

### ISSUE THREAD

**Issue by Proxiweb** [thejameskyle/marionette-wires#35]
Hello,

Thanks for this boilerplate. It's not an issue but I can't figure what's going on : I want to put a form in a modal. I've edited the modal service, everything goes fine, my modal is form shown,  but the modal's view onDomRefresh and onAttach methods aren't fired.

I've added an onDomRefresh with a console log in ModalAlertView... it isn't fired too... I'can't figure why

**Comment by thejameskyle** [comment]
The modal LayoutView itself is never destroyed, it simply uses Bootstraps modal plugin to show and hide itself.

The view inside the modal content region should be firing the onDomRefresh and onAttach triggerMethods. If you can create a reproducible test case I can attempt to debug it.

**Comment by Proxiweb** [comment]
Thanks, I found a workarround but when I'll have fully understand how to write tests with pioneer, I'll push a test case.

**Comment by thejameskyle** [comment]
Let me know when you have something and I'll reopen this
