### ISSUE TITLE
Cannot read property 'Deferred' of undefined

### ISSUE THREAD

**Issue by wss-world** [thejameskyle/marionette-wires#54]
Help me!

**Comment by thejameskyle** [comment]
Backbone.$ is not being set

**Comment by wss-world** [comment]
I'm sorry. I do not understand how to fix this problem. 
The file plugins.js: Backbone. $ = $;

**Comment by thejameskyle** [comment]
Somehow that's getting messed up, I have no way of debugging it further for you. Go ask in the marionette gitter channel.

**Comment by editstudio** [comment]
@wss-world I had the same problem when I upgraded the "babelify" package from "^5.0.3" to "^6.0.2". After reverting, the error no longer appeared.

**Comment by MarcSky** [comment]
I have exactly the same error and to wss-world! Deffered error with how to solve it! Help!

**Comment by thejameskyle** [comment]
Stop using wires as a boilerplate. I'm not going to support that.
