### ISSUE TITLE
A mistake by the 'gulp-mocha'

### ISSUE THREAD

**Issue by wss-world** [thejameskyle/marionette-wires#55]
![screenshot 2015-05-14 18 36 57](https://cloud.githubusercontent.com/assets/3687047/7635199/40a92e62-fa68-11e4-9178-b6f64fc781af.png)

**Comment by MarcSky** [comment]
I install the same project from scratch and I also drops the same mistake. Similarly, a report shows. Please help.

**Comment by MarcSky** [comment]
I have this problem! have to it solve! Help
