### ISSUE TITLE
Modals not closing

### ISSUE THREAD

**Issue by marc314** [thejameskyle/marionette-wires#60]
Hey guys,

I guess this is moreso an issue with the backbone-modals-service plugin, but I have noticed on my PC/mac when I run wires and navigate to colors=> show and force a modal open by clicking destroy, I cannot cancel the dialog. Worth looking into?

**Comment by belackriv** [comment]
I did this: https://github.com/thejameskyle/backbone-service-modals/pull/1 and they started working.

**Comment by vedi** [comment]
+1
any chances to fix this?

**Comment by thejameskyle** [comment]
Waiting on https://github.com/thejameskyle/backbone-service-modals/pull/1
