### ISSUE TITLE
Stop using the Controller Class for application architecture

### ISSUE THREAD

**Issue by jmeas** [thejameskyle/marionette-wires#7]
Sure, I get it – Applications and Modules have a lot of necessary features, so you use Controllers to boldly state that you aren't using those features. But at what cost?

If I show someone an app where Applications and Modules are used as the base objects, they're quickly going to pick up on those things being the main organizational structures. But a Controller? That Class has long been criticized for its poor name, because everyone associates a Controller with a specific action in MVC frameworks. For those acquainted with Marionette, they'll know that's really just a white-label Class. But in neither case will people associate it with application-level architecture, I think, unless you tell them. Sure, it could be in the README or something, but I think it just makes Marionette look really bad.

Using Object makes it marginally better, but still not that good. I think there should be some sort of Class with a name like Application or Module that more clearly communicates what's going on.

Otherwise good stuff here :+1:

**Comment by thejameskyle** [comment]
This was done forever ago.
